### ISSUE TITLE
2:CSSをBootstrapと共に設定する

### ISSUE THREAD

**Issue by Takuya-Yamamot** [Takuya-Yamamot/kakeibo#3]
# Issue
アプリのデザイン面を実装したい。シンプリに見やすい状態で。

関連ブランチ
https://github.com/Takuya-Yamamot/kakeibo/pull/5
## Task Description 

**Problem to solve :**
家計簿アプリのデザイン

**Solution:**
Bootstrapを用いて家計簿アプリのデザイン全般を行う。

**Time estimated to complete:**
3h

## Task checklist 

- [x] Bootstrap導入方法を調べる
- [x] Bootstrap documentationを確認する
- [x] Bootstrapをrailsアプリに導入
- [x] index.html.erbの編集
- [x] new.html.erbの編集
- [x] edit.html.erbの編集
- [x] show.html.erbの編集
- [x] loaclhostの確認
- [x] git push
- [x] 実際にherokuにデプロイできるか確認する

## Overview
bootstrapの設定は簡単で楽しい。

**Investigation time：**1h
**Implementation time：**2.5h
